export const optimumHeaderTheme: any = {
  light: {
    '--el-header-optimum-color': '#000000',
    '--el-header-optimum-hover-color': 'var(--el-color-primary)',
    '--el-header-optimum-active-color': 'var(--el-color-primary)',
    '--el-header-optimum-hover-bg-color': '#f4f4f5',
    '--el-header-optimum-active-bg-color': 'var(--el-color-primary-light-8)',
    '--el-header-optimum-border-color': 'var(--el-color-primary)',
  },
  inverted: {
    '--el-header-optimum-color': '#ffffff',
    '--el-header-optimum-hover-color': 'var(--el-color-primary)',
    '--el-header-optimum-active-color': '#ffffff',
    '--el-header-optimum-hover-bg-color': 'transparent',
    '--el-header-optimum-active-bg-color': 'var(--el-color-primary)',
    '--el-header-optimum-border-color': 'var(--el-color-primary)',
  },
  dark: {
    '--el-header-optimum-color': '#E5EAF3',
    '--el-header-optimum-hover-color': 'var(--el-color-primary)',
    '--el-header-optimum-active-color': 'var(--el-color-primary)',
    '--el-header-optimum-hover-bg-color': 'var(--el-color-primary-light-9)',
    '--el-header-optimum-active-bg-color': 'var(--el-color-primary-light-8)',
    '--el-header-optimum-border-color': 'var(--el-color-primary)',
  },
};

export const headerTheme: any = {
  light: {
    '--el-header-bg-color': '#ffffff',
    '--el-header-text-color': '#303133',
    '--el-header-text-color-regular': '#606266',
  },
  inverted: {
    '--el-header-bg-color': '#141414',
    '--el-header-text-color': '#E5EAF3',
    '--el-header-text-color-regular': '#CFD3DC',
  },
  dark: {
    '--el-header-bg-color': '#141414',
    '--el-header-text-color': '#E5EAF3',
    '--el-header-text-color-regular': '#CFD3DC',
  },
};

export const asideTheme: any = {
  light: {
    '--el-aside-logo-text-color': '#303133',
  },
  inverted: {
    '--el-aside-logo-text-color': '#E5EAF3',
  },
  dark: {
    '--el-aside-logo-text-color': '#E5EAF3',
  },
};

export const pageTheme: any = {
  light: {
    '--page-bg-color': '#f7f8fa',
    '--btn-icon-color': 'rgba(0,0,0,.5)',
    '--btn-icon-hover-bg': 'rgba(0,0,0,.05)',
    '--btn-icon-active-bg': 'rgba(0,0,0,.08)',
    '--action-btn-border': 'rgba(0,0,0,.1)',
    '--action-btn-color': 'var(--el-text-color-regular)',
    '--action-btn-hover-bg': 'var(--el-fill-color-light)',
    '--chat-bubble-user-bg': '#e8f4ff',
    '--chat-bubble-user-color': '#1a1a1a',
    '--chat-bubble-ai-bg': 'var(--el-bg-color)',
    '--chat-bubble-ai-color': 'var(--el-text-color-primary)',
    '--media-sender-shadow': '0 2px 12px rgba(0,0,0,.06)',
    '--context-menu-shadow': '0 6px 16px rgba(0,0,0,.12)',
    '--scrollbar-thumb-bg': '#e5e7eb',
    '--scrollbar-track-bg': 'transparent',
    '--ref-upload-bg': '#fafafa',
    '--ref-upload-border': '#d1d5db',
    '--ref-upload-hover-border': 'var(--el-color-primary)',
    '--login-left-gradient': 'linear-gradient(233deg, rgba(113,161,255,.6) 17.67%, rgba(154,219,255,.6) 70.4%)',
    '--new-chat-btn-color': 'var(--el-text-color-regular)',
    '--new-chat-btn-hover-bg': 'var(--el-fill-color-light)',
    '--msg-time-color': 'var(--el-text-color-placeholder)',
    '--copy-btn-color': 'var(--el-text-color-secondary)',
    '--copy-btn-hover-bg': 'var(--el-fill-color-light)',
    '--edit-card-bg': '#fafafa',
    '--edit-card-border': '#e5e7eb',
    '--toolcall-card-bg': '#fafafa',
    '--toolcall-card-border': '#e5e7eb',
    '--toolcall-card-shadow': '0 1px 3px rgba(0,0,0,.06)',
    '--history-item-hover-bg': 'var(--el-fill-color-light)',
    '--history-item-active-bg': 'var(--el-fill-color)',
    '--knowledge-list-bg': '#fafafa',
    '--knowledge-list-border': '#e5e7eb',
    '--model-select-border': 'var(--el-border-color-light)',
    '--model-select-hover-border': 'var(--el-color-primary)',
    '--file-select-border': 'var(--el-border-color-light)',
    '--file-select-hover-bg': 'var(--el-fill-color-light)',
    '--media-bubble-shadow': '0 2px 8px rgba(0,0,0,.06)',
    '--aside-shadow': '2px 0 8px rgba(0,0,0,.04)',
    '--label-color': 'var(--el-text-color-regular)',
  },
  inverted: {
    '--page-bg-color': '#141414',
    '--btn-icon-color': 'var(--el-text-color-regular)',
    '--btn-icon-hover-bg': 'var(--el-fill-color-light)',
    '--btn-icon-active-bg': 'var(--el-fill-color)',
    '--action-btn-border': 'var(--el-border-color)',
    '--action-btn-color': 'var(--el-text-color-regular)',
    '--action-btn-hover-bg': 'var(--el-fill-color-light)',
    '--chat-bubble-user-bg': 'var(--el-color-primary-light-5)',
    '--chat-bubble-user-color': '#ffffff',
    '--chat-bubble-ai-bg': 'var(--el-bg-color)',
    '--chat-bubble-ai-color': 'var(--el-text-color-primary)',
    '--media-sender-shadow': 'none',
    '--context-menu-shadow': '0 6px 16px rgba(0,0,0,.3)',
    '--scrollbar-thumb-bg': 'var(--el-fill-color)',
    '--scrollbar-track-bg': 'transparent',
    '--ref-upload-bg': 'var(--el-fill-color-light)',
    '--ref-upload-border': 'var(--el-border-color)',
    '--ref-upload-hover-border': 'var(--el-color-primary)',
    '--login-left-gradient': 'linear-gradient(233deg, rgba(113,161,255,.15) 17.67%, rgba(154,219,255,.15) 70.4%)',
    '--new-chat-btn-color': 'var(--el-text-color-regular)',
    '--new-chat-btn-hover-bg': 'var(--el-fill-color-light)',
    '--msg-time-color': 'var(--el-text-color-placeholder)',
    '--copy-btn-color': 'var(--el-text-color-secondary)',
    '--copy-btn-hover-bg': 'var(--el-fill-color-light)',
    '--edit-card-bg': 'var(--el-fill-color-light)',
    '--edit-card-border': 'var(--el-border-color)',
    '--toolcall-card-bg': 'var(--el-fill-color-light)',
    '--toolcall-card-border': 'var(--el-border-color)',
    '--toolcall-card-shadow': 'none',
    '--history-item-hover-bg': 'var(--el-fill-color-light)',
    '--history-item-active-bg': 'var(--el-fill-color)',
    '--knowledge-list-bg': 'var(--el-fill-color-light)',
    '--knowledge-list-border': 'var(--el-border-color)',
    '--model-select-border': 'var(--el-border-color-light)',
    '--model-select-hover-border': 'var(--el-color-primary)',
    '--file-select-border': 'var(--el-border-color-light)',
    '--file-select-hover-bg': 'var(--el-fill-color-light)',
    '--media-bubble-shadow': 'none',
    '--aside-shadow': 'none',
    '--label-color': 'var(--el-text-color-regular)',
  },
  dark: {
    '--page-bg-color': '#141414',
    '--btn-icon-color': 'var(--el-text-color-regular)',
    '--btn-icon-hover-bg': 'var(--el-fill-color-light)',
    '--btn-icon-active-bg': 'var(--el-fill-color)',
    '--action-btn-border': 'var(--el-border-color)',
    '--action-btn-color': 'var(--el-text-color-regular)',
    '--action-btn-hover-bg': 'var(--el-fill-color-light)',
    '--chat-bubble-user-bg': 'var(--el-color-primary-light-5)',
    '--chat-bubble-user-color': '#ffffff',
    '--chat-bubble-ai-bg': 'var(--el-bg-color)',
    '--chat-bubble-ai-color': 'var(--el-text-color-primary)',
    '--media-sender-shadow': 'none',
    '--context-menu-shadow': '0 6px 16px rgba(0,0,0,.3)',
    '--scrollbar-thumb-bg': 'var(--el-fill-color)',
    '--scrollbar-track-bg': 'transparent',
    '--ref-upload-bg': 'var(--el-fill-color-light)',
    '--ref-upload-border': 'var(--el-border-color)',
    '--ref-upload-hover-border': 'var(--el-color-primary)',
    '--login-left-gradient': 'linear-gradient(233deg, rgba(113,161,255,.15) 17.67%, rgba(154,219,255,.15) 70.4%)',
    '--new-chat-btn-color': 'var(--el-text-color-regular)',
    '--new-chat-btn-hover-bg': 'var(--el-fill-color-light)',
    '--msg-time-color': 'var(--el-text-color-placeholder)',
    '--copy-btn-color': 'var(--el-text-color-secondary)',
    '--copy-btn-hover-bg': 'var(--el-fill-color-light)',
    '--edit-card-bg': 'var(--el-fill-color-light)',
    '--edit-card-border': 'var(--el-border-color)',
    '--toolcall-card-bg': 'var(--el-fill-color-light)',
    '--toolcall-card-border': 'var(--el-border-color)',
    '--toolcall-card-shadow': 'none',
    '--history-item-hover-bg': 'var(--el-fill-color-light)',
    '--history-item-active-bg': 'var(--el-fill-color)',
    '--knowledge-list-bg': 'var(--el-fill-color-light)',
    '--knowledge-list-border': 'var(--el-border-color)',
    '--model-select-border': 'var(--el-border-color-light)',
    '--model-select-hover-border': 'var(--el-color-primary)',
    '--file-select-border': 'var(--el-border-color-light)',
    '--file-select-hover-bg': 'var(--el-fill-color-light)',
    '--media-bubble-shadow': 'none',
    '--aside-shadow': 'none',
    '--label-color': 'var(--el-text-color-regular)',
  },
};

export const menuTheme: any = {
  light: {
    '--el-menu-bg-color': '#ffffff',
    '--el-menu-hover-bg-color': '#f4f4f5',
    '--el-menu-active-bg-color': 'var(--el-color-primary-light-8)',
    '--el-menu-text-color': '#333639',
    '--el-menu-hover-text-color': 'var(--el-color-primary)',
    '--el-menu-active-text-color': 'var(--el-color-primary)',
    '--el-menu-border-left-color': 'var(--el-color-primary)',
  },
  inverted: {
    '--el-menu-bg-color': '#191A20',
    '--el-menu-hover-bg-color': '#000000',
    '--el-menu-active-bg-color': 'var(--el-color-primary)',
    '--el-menu-text-color': '#dBd8d8',
    '--el-menu-hover-text-color': '#ffffff',
    '--el-menu-active-text-color': '#ffffff',
    '--el-menu-border-left-color': 'transparent',
  },
  dark: {
    '--el-menu-bg-color': '#141414',
    '--el-menu-hover-bg-color': 'var(--el-color-primary-light-9)',
    '--el-menu-active-bg-color': 'var(--el-color-primary-light-8)',
    '--el-menu-text-color': '#e5eAf3',
    '--el-menu-hover-text-color': 'var(--el-color-primary)',
    '--el-menu-active-text-color': 'var(--el-color-primary)',
    '--el-menu-border-left-color': 'var(--el-color-primary)',
  },
};
